version: '3'

services:
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        command: python -m flask run -h 0.0.0.0 -p 5000
        environment:
            - FlASK_APP=wsgi.py
            - FLASK_ENV=development
        volumes:
            - ./:/api
        depends_on:
            - migration

    migration:
        build:
            context: ./
            dockerfile: Dockerfile
        command: python -m flask db upgrade
        environment:
            - FLASK_ENV=development
        volumes:
            - ./:/api